name: Deploy Laravel

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /var/www/vhosts/fu.edu.sd/public_html/repositories/sdfu_api

            git fetch origin

            git reset --hard origin/dev

            composer install --no-dev --prefer-dist --optimize-autoloader

            php artisan optimize:clear

            php artisan config:cache

            php artisan route:cache

            php artisan view:cache

            php artisan migrate --force

            chmod -R 775 storage bootstrap/cache
